exclude: '/\.history/.*'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: mixed-line-ending
        args: ['--fix=no']
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.6.0
#     hooks:
#     -   id: mypy
#         args: [--strict]
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml", "-r", "."]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8, flake8-print]
